//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mhxy.App.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mhxy.App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] dm {
            get {
                object obj = ResourceManager.GetObject("dm", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 3FEC0200400800E007F8$0$0.0.40$16
        ///200C03FF8$1$0.0.19$16
        ///78180200C068198E1F00$2$0.0.36$15
        ///78180200C028198E1F00$2$0.0.35$15
        ///701802044088318D1F38$3$0.0.39$16
        ///701802044088318D1F18$3$0.0.38$16
        ///00201C0E871383E07FF801$4$0.0.44$15
        ///00201C0E871303E07FF801$4$0.0.43$15
        ///FF986208410821062078$5$0.0.41$16
        ///FF986208410821062078$5$0.0.40$16
        ///3FEC6208410821861878$6$0.0.43$16
        ///80100200C1F8E1E03000$7$0.0.25$16
        ///80100200C1F8C1E03000$7$0.0.24$16
        ///787CF20C4088318F1F18$8$0.0.49$16
        ///787CF20C4088318F0E18$8$0.0.47$16
        ///787CF20C4 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string lvl {
            get {
                return ResourceManager.GetString("lvl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] reg {
            get {
                object obj = ResourceManager.GetObject("reg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] 任务栏_捉鬼 {
            get {
                object obj = ResourceManager.GetObject("任务栏_捉鬼", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] 战斗_展开 {
            get {
                object obj = ResourceManager.GetObject("战斗_展开", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] 战斗_收缩 {
            get {
                object obj = ResourceManager.GetObject("战斗_收缩", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] 界面_任务栏 {
            get {
                object obj = ResourceManager.GetObject("界面_任务栏", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] 界面_包裹 {
            get {
                object obj = ResourceManager.GetObject("界面_包裹", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] 界面_展开任务栏 {
            get {
                object obj = ResourceManager.GetObject("界面_展开任务栏", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] 界面_指引 {
            get {
                object obj = ResourceManager.GetObject("界面_指引", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] 界面_活动 {
            get {
                object obj = ResourceManager.GetObject("界面_活动", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] 界面_队伍 {
            get {
                object obj = ResourceManager.GetObject("界面_队伍", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] 界面_队伍栏 {
            get {
                object obj = ResourceManager.GetObject("界面_队伍栏", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] 队伍_创建 {
            get {
                object obj = ResourceManager.GetObject("队伍_创建", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] 队伍_助战 {
            get {
                object obj = ResourceManager.GetObject("队伍_助战", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] 队伍_匹配 {
            get {
                object obj = ResourceManager.GetObject("队伍_匹配", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] 队伍_喊话 {
            get {
                object obj = ResourceManager.GetObject("队伍_喊话", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] 队伍_捉鬼 {
            get {
                object obj = ResourceManager.GetObject("队伍_捉鬼", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] 队伍_暂离 {
            get {
                object obj = ResourceManager.GetObject("队伍_暂离", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] 队伍_离线 {
            get {
                object obj = ResourceManager.GetObject("队伍_离线", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] 队伍_请离 {
            get {
                object obj = ResourceManager.GetObject("队伍_请离", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
